---
title: "Quality Check results - SAS to R transition"
author: "Jithin Sam Varghese"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Specify objective

The objective for this QC process is the following:
- Transfer from *DashboardData_07.07.2020_Claire.sas* and *Claire_dataUpdate2.R* to *~/c19dashboard/dashboard data/.* scripts.   
- Identify interim files which could be QC-ed   
- Identify QC items: number of rows, variable names, cross-tabulations, summary datasets, equivalence of subsets

## 1.1 Identify files

From DashboardData_07.07.2020_Claire.sas   
- At Line 500: Covidtimeseries_pop   
- At Line 789: mergedsocial  

From Claire_dataUpdate2.R   
- At Line 210: final_hosptest_ts
- At Line 228: final_hosptest_ts4
- At Line 236: final_hosptest_ts6
- At Line 288: merged_covidtimeseries
- At Line 291: merged_covidtimeseries1
- At Line 357: covidtimeseries2
- At Line 421: final_merged_covidtimeseries
- At Line 488: final_merged_covidtimeseries
- At Line 500: final_merged_covidtimeseries1
- At Line 508: final_merged_covidtimeseries2
- At Line 537: final_merged_covidtimeseries_x
- At Line 563: final_merged_covidtimeseries1
- At Line 600: merged_nationalraw
- At Line 627: merged_nationalraw2
- At Line 654: final_merged_nationalraw
- At Line 706: final_merged_nationalraw
- At Line 869: CVImerged
- At Line 905: ressegToNR
- At Line 960: contristates
- At Line 1072: outcomes
- At Line 1110: outcomes_mort_pre
- At Line 1138: merged
- At Line 1251: chronic_state
- At Line 1345: indices_data
- At Line 1370: indices_data
- At Line 1447: casesdata
- At Line 1470: VaccineTracker9
- At Line 1505: VaccineTracker0
- At Line 1559: merge1
- At Line 1573: texas
- At Line 1588: merge2
- At Line 1605: merge3

## 1.2 Identify checks which are applicable to datasets

The following checks would be carried out for all timeseries datasets:    
1. Number of rows   
2. Variable names    
3. Formats of variables    
4. Summaries of all variables (N, N missing, Mean, SD, Min, Max)     
5. Equivalence of random subset: Once the dataset has passed the previous items, a random sample would be picked and checked for equivalence     

The following checks would be carried out for all static datasets:    
1. Number of rows   
2. Variable names    
3. Formats of variables    
4. Summaries of all variables (N, N missing, Mean, SD, Min, Max)     
5. Equivalence of random subset: Once the dataset has passed the previous items, a random sample would be picked and checked for equivalence     

## 1.3 Notes for QC

1. One "qc##_" script per interim dataset.    
2. The QC script should contain information on how to replicate the original dataset using existing R scripts on the repository.    

